FROM node:20-bullseye

#Install build dependencies for native modules (node-pty)
# 'make,'g++', and 'python3' are required for node-gpy to compile c++ code
RUN apt-get update && apt-get install -y \
    python3 \
    make \
    g++ \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

EXPOSE 3000

RUN mkdir /workspace

CMD ["node", "server.js"]